// Code generated by protoc-gen-go.
// source: chatroom.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	chatroom.proto

It has these top-level messages:
	EnterRoomReq
	EnterRoomRsp
	MemberEnter
	UpMessage
	DownMessage
	ExitRoomReq
	ExitRoomRsp
	Message
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Message_MessageType int32

const (
	Message_ENTER_ROOM_REQ Message_MessageType = 1
	Message_ENTER_ROOM_RSP Message_MessageType = 2
	Message_MEMBER_ENTER   Message_MessageType = 3
	Message_UP_MESSAGE     Message_MessageType = 4
	Message_DOWN_MESSAGE   Message_MessageType = 5
	Message_EXIT_ROOM_REQ  Message_MessageType = 6
	Message_EXIT_ROOM_RSP  Message_MessageType = 7
)

var Message_MessageType_name = map[int32]string{
	1: "ENTER_ROOM_REQ",
	2: "ENTER_ROOM_RSP",
	3: "MEMBER_ENTER",
	4: "UP_MESSAGE",
	5: "DOWN_MESSAGE",
	6: "EXIT_ROOM_REQ",
	7: "EXIT_ROOM_RSP",
}
var Message_MessageType_value = map[string]int32{
	"ENTER_ROOM_REQ": 1,
	"ENTER_ROOM_RSP": 2,
	"MEMBER_ENTER":   3,
	"UP_MESSAGE":     4,
	"DOWN_MESSAGE":   5,
	"EXIT_ROOM_REQ":  6,
	"EXIT_ROOM_RSP":  7,
}

func (x Message_MessageType) Enum() *Message_MessageType {
	p := new(Message_MessageType)
	*p = x
	return p
}
func (x Message_MessageType) String() string {
	return proto1.EnumName(Message_MessageType_name, int32(x))
}
func (x *Message_MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(Message_MessageType_value, data, "Message_MessageType")
	if err != nil {
		return err
	}
	*x = Message_MessageType(value)
	return nil
}
func (Message_MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

type EnterRoomReq struct {
	RoomName         *string `protobuf:"bytes,1,opt,name=roomName" json:"roomName,omitempty"`
	NickName         *string `protobuf:"bytes,2,opt,name=nickName" json:"nickName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnterRoomReq) Reset()                    { *m = EnterRoomReq{} }
func (m *EnterRoomReq) String() string            { return proto1.CompactTextString(m) }
func (*EnterRoomReq) ProtoMessage()               {}
func (*EnterRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EnterRoomReq) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

func (m *EnterRoomReq) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

type EnterRoomRsp struct {
	Errno            *int32  `protobuf:"varint,1,opt,name=errno" json:"errno,omitempty"`
	ID               *uint32 `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnterRoomRsp) Reset()                    { *m = EnterRoomRsp{} }
func (m *EnterRoomRsp) String() string            { return proto1.CompactTextString(m) }
func (*EnterRoomRsp) ProtoMessage()               {}
func (*EnterRoomRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EnterRoomRsp) GetErrno() int32 {
	if m != nil && m.Errno != nil {
		return *m.Errno
	}
	return 0
}

func (m *EnterRoomRsp) GetID() uint32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

type MemberEnter struct {
	ID               *uint32 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	NickName         *string `protobuf:"bytes,2,opt,name=nickName" json:"nickName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MemberEnter) Reset()                    { *m = MemberEnter{} }
func (m *MemberEnter) String() string            { return proto1.CompactTextString(m) }
func (*MemberEnter) ProtoMessage()               {}
func (*MemberEnter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MemberEnter) GetID() uint32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *MemberEnter) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

type UpMessage struct {
	Message          []byte `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Length           *int32 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpMessage) Reset()                    { *m = UpMessage{} }
func (m *UpMessage) String() string            { return proto1.CompactTextString(m) }
func (*UpMessage) ProtoMessage()               {}
func (*UpMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *UpMessage) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type DownMessage struct {
	Message          []byte  `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Length           *int32  `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	NickName         *string `protobuf:"bytes,3,opt,name=nickName" json:"nickName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DownMessage) Reset()                    { *m = DownMessage{} }
func (m *DownMessage) String() string            { return proto1.CompactTextString(m) }
func (*DownMessage) ProtoMessage()               {}
func (*DownMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DownMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *DownMessage) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *DownMessage) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

type ExitRoomReq struct {
	RoomName         *string `protobuf:"bytes,1,opt,name=roomName" json:"roomName,omitempty"`
	NickName         *string `protobuf:"bytes,2,opt,name=nickName" json:"nickName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExitRoomReq) Reset()                    { *m = ExitRoomReq{} }
func (m *ExitRoomReq) String() string            { return proto1.CompactTextString(m) }
func (*ExitRoomReq) ProtoMessage()               {}
func (*ExitRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ExitRoomReq) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

func (m *ExitRoomReq) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

type ExitRoomRsp struct {
	Errno            *int32 `protobuf:"varint,1,opt,name=errno" json:"errno,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ExitRoomRsp) Reset()                    { *m = ExitRoomRsp{} }
func (m *ExitRoomRsp) String() string            { return proto1.CompactTextString(m) }
func (*ExitRoomRsp) ProtoMessage()               {}
func (*ExitRoomRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ExitRoomRsp) GetErrno() int32 {
	if m != nil && m.Errno != nil {
		return *m.Errno
	}
	return 0
}

type Message struct {
	Type             *Message_MessageType `protobuf:"varint,1,opt,name=type,enum=proto.Message_MessageType" json:"type,omitempty"`
	EnterRoomReq     *EnterRoomReq        `protobuf:"bytes,2,opt,name=enterRoomReq" json:"enterRoomReq,omitempty"`
	EnterRoomRsp     *EnterRoomRsp        `protobuf:"bytes,3,opt,name=enterRoomRsp" json:"enterRoomRsp,omitempty"`
	MemberEnter      *MemberEnter         `protobuf:"bytes,4,opt,name=memberEnter" json:"memberEnter,omitempty"`
	UpMessage        *UpMessage           `protobuf:"bytes,5,opt,name=upMessage" json:"upMessage,omitempty"`
	DownMessage      *DownMessage         `protobuf:"bytes,6,opt,name=downMessage" json:"downMessage,omitempty"`
	ExitRoomReq      *ExitRoomReq         `protobuf:"bytes,7,opt,name=exitRoomReq" json:"exitRoomReq,omitempty"`
	ExitRoomRsp      *ExitRoomRsp         `protobuf:"bytes,8,opt,name=exitRoomRsp" json:"exitRoomRsp,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto1.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Message) GetType() Message_MessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Message_ENTER_ROOM_REQ
}

func (m *Message) GetEnterRoomReq() *EnterRoomReq {
	if m != nil {
		return m.EnterRoomReq
	}
	return nil
}

func (m *Message) GetEnterRoomRsp() *EnterRoomRsp {
	if m != nil {
		return m.EnterRoomRsp
	}
	return nil
}

func (m *Message) GetMemberEnter() *MemberEnter {
	if m != nil {
		return m.MemberEnter
	}
	return nil
}

func (m *Message) GetUpMessage() *UpMessage {
	if m != nil {
		return m.UpMessage
	}
	return nil
}

func (m *Message) GetDownMessage() *DownMessage {
	if m != nil {
		return m.DownMessage
	}
	return nil
}

func (m *Message) GetExitRoomReq() *ExitRoomReq {
	if m != nil {
		return m.ExitRoomReq
	}
	return nil
}

func (m *Message) GetExitRoomRsp() *ExitRoomRsp {
	if m != nil {
		return m.ExitRoomRsp
	}
	return nil
}

func init() {
	proto1.RegisterType((*EnterRoomReq)(nil), "proto.EnterRoomReq")
	proto1.RegisterType((*EnterRoomRsp)(nil), "proto.EnterRoomRsp")
	proto1.RegisterType((*MemberEnter)(nil), "proto.MemberEnter")
	proto1.RegisterType((*UpMessage)(nil), "proto.UpMessage")
	proto1.RegisterType((*DownMessage)(nil), "proto.DownMessage")
	proto1.RegisterType((*ExitRoomReq)(nil), "proto.ExitRoomReq")
	proto1.RegisterType((*ExitRoomRsp)(nil), "proto.ExitRoomRsp")
	proto1.RegisterType((*Message)(nil), "proto.Message")
	proto1.RegisterEnum("proto.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
}

var fileDescriptor0 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x53, 0xa0, 0x14, 0xa6, 0xb4, 0xd6, 0xf5, 0xd2, 0x18, 0x0f, 0xa6, 0x1e, 0xc4, 0x68,
	0x48, 0xe4, 0x09, 0xd4, 0xb0, 0x31, 0x1c, 0x0a, 0x58, 0x20, 0x7a, 0x23, 0x88, 0x1b, 0x20, 0xda,
	0x3f, 0xb6, 0x35, 0xea, 0x53, 0xf8, 0x92, 0x3e, 0x88, 0xdb, 0xa1, 0xb0, 0x5b, 0xe4, 0xa0, 0xa7,
	0x36, 0xdf, 0xfc, 0x66, 0x76, 0xe7, 0xfb, 0x16, 0xcc, 0xd9, 0x62, 0x9a, 0xc6, 0x61, 0xe8, 0xb7,
	0xa2, 0x38, 0x4c, 0x43, 0xa2, 0xe2, 0xc7, 0x69, 0x43, 0x83, 0x06, 0x29, 0x8b, 0x3d, 0x5e, 0xf1,
	0xd8, 0x2b, 0xb1, 0xa0, 0x96, 0x41, 0xbd, 0xa9, 0xcf, 0x6c, 0xe5, 0x58, 0x69, 0xd6, 0x33, 0x25,
	0x58, 0xce, 0x9e, 0x51, 0x29, 0x65, 0x8a, 0x73, 0x26, 0xf7, 0x24, 0x11, 0x31, 0x40, 0x65, 0x71,
	0x1c, 0x84, 0xd8, 0xa0, 0x12, 0x80, 0x52, 0xb7, 0x83, 0xa8, 0xe1, 0x9c, 0x83, 0xee, 0x32, 0xff,
	0x91, 0xc5, 0xd8, 0x90, 0x97, 0x32, 0xcc, 0xd8, 0x31, 0xf7, 0x02, 0xea, 0xe3, 0xc8, 0x65, 0x49,
	0x32, 0x9d, 0x33, 0xb2, 0x07, 0x9a, 0xbf, 0xfa, 0x45, 0xbe, 0x41, 0x4c, 0xa8, 0xbe, 0xb0, 0x60,
	0x9e, 0x2e, 0x90, 0x56, 0x9d, 0x2b, 0xd0, 0x3b, 0xe1, 0x7b, 0xf0, 0x57, 0xbe, 0x70, 0x5e, 0x19,
	0xcf, 0xbb, 0x04, 0x9d, 0x7e, 0x2c, 0xd3, 0xff, 0xac, 0x7e, 0x24, 0xb5, 0xfc, 0xda, 0xdc, 0xf9,
	0x2e, 0x83, 0xb6, 0xbe, 0x4f, 0x13, 0x2a, 0xe9, 0x67, 0xb4, 0x9a, 0x64, 0xb6, 0x0f, 0x57, 0xae,
	0xb7, 0xf2, 0xea, 0xfa, 0x3b, 0xe2, 0x04, 0xe1, 0x76, 0x32, 0x29, 0x02, 0x3c, 0x49, 0x6f, 0x1f,
	0xe4, 0x1d, 0x85, 0x74, 0x0a, 0x68, 0x12, 0xe1, 0x1e, 0xbb, 0x50, 0x7e, 0xb5, 0x53, 0xd0, 0x7d,
	0xe1, 0xbc, 0x5d, 0x41, 0x92, 0x6c, 0xae, 0x21, 0x32, 0x39, 0x81, 0xfa, 0xdb, 0xda, 0x75, 0x5b,
	0x45, 0xcc, 0xca, 0x31, 0x91, 0x06, 0x9f, 0xf6, 0x24, 0xcc, 0xb6, 0xab, 0x85, 0x69, 0x72, 0x0c,
	0x1c, 0x64, 0xc2, 0x53, 0x5b, 0x2b, 0x80, 0xb2, 0xdb, 0x32, 0xc8, 0x37, 0xa9, 0xed, 0x06, 0x93,
	0xc8, 0xf9, 0x52, 0xb2, 0x37, 0x24, 0xec, 0x22, 0x60, 0xd2, 0xde, 0x88, 0x7a, 0x13, 0xaf, 0xdf,
	0x77, 0x27, 0x1e, 0xbd, 0xb3, 0x94, 0x6d, 0x6d, 0x38, 0xb0, 0x4a, 0x3c, 0xbc, 0x86, 0x4b, 0xdd,
	0x1b, 0x2e, 0x62, 0xc9, 0x2a, 0xf3, 0x17, 0x01, 0xe3, 0xc1, 0xc4, 0xa5, 0xc3, 0xe1, 0xf5, 0x2d,
	0xb5, 0x2a, 0x19, 0xd1, 0xe9, 0xdf, 0xf7, 0x36, 0x8a, 0x4a, 0xf6, 0xc1, 0xa0, 0x0f, 0xdd, 0x91,
	0x18, 0x5d, 0xdd, 0x92, 0xf8, 0x64, 0xed, 0x27, 0x00, 0x00, 0xff, 0xff, 0x83, 0x9e, 0x6a, 0xde,
	0x4b, 0x03, 0x00, 0x00,
}
