// Code generated by protoc-gen-go.
// source: knot.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	knot.proto

It has these top-level messages:
	NewAgentReq
	NewAgentRsp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NewAgentReq struct {
	Uuid             []byte `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NewAgentReq) Reset()                    { *m = NewAgentReq{} }
func (m *NewAgentReq) String() string            { return proto.CompactTextString(m) }
func (*NewAgentReq) ProtoMessage()               {}
func (*NewAgentReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NewAgentReq) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

type NewAgentRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NewAgentRsp) Reset()                    { *m = NewAgentRsp{} }
func (m *NewAgentRsp) String() string            { return proto.CompactTextString(m) }
func (*NewAgentRsp) ProtoMessage()               {}
func (*NewAgentRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*NewAgentReq)(nil), "pb.NewAgentReq")
	proto.RegisterType((*NewAgentRsp)(nil), "pb.NewAgentRsp")
}

var fileDescriptor0 = []byte{
	// 75 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xce, 0xcb, 0x2f,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92, 0xe6, 0xe2, 0xf6, 0x4b,
	0x2d, 0x77, 0x4c, 0x4f, 0xcd, 0x2b, 0x09, 0x4a, 0x2d, 0x14, 0xe2, 0xe1, 0x62, 0x29, 0x2d, 0xcd,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x51, 0xe2, 0x45, 0x92, 0x2c, 0x2e, 0x00, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xd0, 0x2f, 0xf2, 0xb4, 0x3c, 0x00, 0x00, 0x00,
}
