// Code generated by protoc-gen-go.
// source: knot.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	knot.proto

It has these top-level messages:
	ConnReq
	ConnRsp
	NewAgentReq
	NewAgentRsp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ConnReq struct {
	AccessKey        []byte `protobuf:"bytes,1,opt,name=AccessKey" json:"AccessKey,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ConnReq) Reset()                    { *m = ConnReq{} }
func (m *ConnReq) String() string            { return proto.CompactTextString(m) }
func (*ConnReq) ProtoMessage()               {}
func (*ConnReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConnReq) GetAccessKey() []byte {
	if m != nil {
		return m.AccessKey
	}
	return nil
}

type ConnRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ConnRsp) Reset()                    { *m = ConnRsp{} }
func (m *ConnRsp) String() string            { return proto.CompactTextString(m) }
func (*ConnRsp) ProtoMessage()               {}
func (*ConnRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NewAgentReq struct {
	UUID             []byte `protobuf:"bytes,1,opt,name=UUID" json:"UUID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NewAgentReq) Reset()                    { *m = NewAgentReq{} }
func (m *NewAgentReq) String() string            { return proto.CompactTextString(m) }
func (*NewAgentReq) ProtoMessage()               {}
func (*NewAgentReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NewAgentReq) GetUUID() []byte {
	if m != nil {
		return m.UUID
	}
	return nil
}

type NewAgentRsp struct {
	Errno            *int32 `protobuf:"varint,1,opt,name=errno" json:"errno,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NewAgentRsp) Reset()                    { *m = NewAgentRsp{} }
func (m *NewAgentRsp) String() string            { return proto.CompactTextString(m) }
func (*NewAgentRsp) ProtoMessage()               {}
func (*NewAgentRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NewAgentRsp) GetErrno() int32 {
	if m != nil && m.Errno != nil {
		return *m.Errno
	}
	return 0
}

func init() {
	proto.RegisterType((*ConnReq)(nil), "pb.ConnReq")
	proto.RegisterType((*ConnRsp)(nil), "pb.ConnRsp")
	proto.RegisterType((*NewAgentReq)(nil), "pb.NewAgentReq")
	proto.RegisterType((*NewAgentRsp)(nil), "pb.NewAgentRsp")
}

var fileDescriptor0 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xce, 0xcb, 0x2f,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92, 0xe1, 0x62, 0x77, 0xce,
	0xcf, 0xcb, 0x0b, 0x4a, 0x2d, 0x14, 0x12, 0xe4, 0xe2, 0x74, 0x4c, 0x4e, 0x4e, 0x2d, 0x2e, 0xf6,
	0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x51, 0xe2, 0x84, 0xca, 0x16, 0x17, 0x28, 0x49,
	0x73, 0x71, 0xfb, 0xa5, 0x96, 0x3b, 0xa6, 0xa7, 0xe6, 0x95, 0x80, 0x14, 0xf3, 0x70, 0xb1, 0x84,
	0x86, 0x7a, 0xba, 0x40, 0xd5, 0xc9, 0x20, 0x49, 0x16, 0x17, 0x08, 0xf1, 0x72, 0xb1, 0xa6, 0x16,
	0x15, 0xe5, 0xe5, 0x83, 0x65, 0x59, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xd4, 0xe8, 0x54,
	0x74, 0x00, 0x00, 0x00,
}
